### ISSUE TITLE
[Feature Request] Canonical Links

### ISSUE THREAD

**Issue by CybrZr00** [jsakamoto/Toolbelt.Blazor.HeadElement#1]
Would it be possible, in a future release to add a ByLink() function so we are able to set the canonical address of each page?

e.g:

> ByLink("canonical", "https://foo.com/bar")

Thank you!

**Comment by jsakamoto** [comment]
Thank you for your nice feature request! 

This feature also helps change favicon dynamically.

I'll try to implement this feature.

**Comment by jsakamoto** [comment]
I published Blazor Head Element Helper ver.1.1.0.

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/

And, it supports manipulation of "link" elements.
Please see also [section C. of README](https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement#c-change-link-elements).

Please try it out! ;)

**Comment by CybrZr00** [comment]
Wow, that's excellent! I'll give it a try later. Thank you!

**Comment by CybrZr00** [comment]
The feature works perfectly, and it even looks like you can add CSS dynamically as well, which of course means we can break up our style sheets, which means faster initial paint on the index!
