### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by Foizman** [jsakamoto/Toolbelt.Blazor.HeadElement#10]
Hi there,

are there any findings as to how Blazor Server in general and this solution in particular behave with regard to search engine optimization?

Are the bots able to crawl such SPA-pages and index all of them?

**Comment by jsakamoto** [comment]
> Are the bots able to crawl such SPA-pages and index all of them?

Maybe, yes they are.

You can inspect the real sample site of a Blazor Server app that URL below.

https://demo-blazor-headelement.azurewebsites.net/

For example, the results of a Google search includes the contents of the sample site above.

https://www.google.com/search?q=Seattle+tour+Blazor+Space+Needle

**Comment by Foizman** [comment]
So with Azure SignalR we can handle large visitor counts an our Blazor-Website.
And with your component we fully can establish a SEO-friendly website that will be crawled correctly even it is a SPA.

Seems to open up a new world on the web.
Cool to know, thank you!
