### ISSUE TITLE
Using Blazor Static Rendering Does Not Work

### ISSUE THREAD

**Issue by TheLazyLemur** [jsakamoto/Toolbelt.Blazor.HeadElement#11]
Dotnet core 5
Blazor Server

When I use Blazor Static Rendering with this library, certain parts of my HTML break, Namely the ```<pre>``` and ```<code>``` tags, if I try to change the title while statically rendering with Blazor these tags behave very strangely. 

Switching to Server Prerender Does however work.

If i simple remove the call to the library weather that be as a service or components, I get this same behavior.

**Comment by jsakamoto** [comment]
@TheLazyLemur Could you attach a sample project that can reproduce the problem to this thread?

**Comment by TheLazyLemur** [comment]
@jsakamoto Sure no poblem here you go. It has two pages one where the title of being edited and the other not. You'll see the problem. Thanks for getting back to me
[RenderingError.zip](https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement/files/5646919/RenderingError.zip)

**Comment by jsakamoto** [comment]
@TheLazyLemur I fixed this issue, and published the new version of the library.

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement.ServerPrerendering/1.2.3

Please try it out.

Thank you for reporting! 👍

**Comment by TheLazyLemur** [comment]
Seems to have worked perfectly. Thanks for the quick help and for making such a useful package.
