### ISSUE TITLE
as-attribute on link-elements

### ISSUE THREAD

**Issue by CobraCalle** [jsakamoto/Toolbelt.Blazor.HeadElement#12]
Hello,

I would like to create different preloadings based on the active page. But I cannot set the as-attibute on a LinkElement... would it be possible to extend this?

Thank you very much

**Comment by jsakamoto** [comment]
Thank you for the nice feature proposal! 

I published a new version of "Blazor Head Element" packages those support "as" attribute of the "link" element. 

- https://www.nuget.org/packages?q=Toolbelt.Blazor.HeadElement

Could you try it out? 
Thanks!

**Comment by CobraCalle** [comment]
Works like a charm... perfect. Thank you very much
