### ISSUE TITLE
Title breaks on URI Fragment "domain.com/test#foo"

### ISSUE THREAD

**Issue by Bubinga** [jsakamoto/Toolbelt.Blazor.HeadElement#15]
Upon page load with the following code, the page is correctly rendered as having the title "Test Title". However, when the user clicks on the link, that title disappears and, in this case, is replaced by the default title of the Blazor App. This code is on a brand new .Net 5 Blazor project with default settings. The issue appears in both Pre-Rendering and in Server Rendering. 
```html
@page "/TitleTest"
@using Toolbelt.Blazor.HeadElement

<Title>Test Title</Title>

<a href="/TitleTest#">example</a>
````

**Comment by jsakamoto** [comment]
Thank you for reporting!

I fixed this problem and released fixed version of this library.

- https://www.nuget.org/packages?q=headelement

Please check it out. 😃

**Comment by Bubinga** [comment]
Thank you for the quick response and fix 👍
