### ISSUE TITLE
[Bug] Problem with polish chars eg. ą,ś,ć,ę

### ISSUE THREAD

**Issue by gaffkins** [jsakamoto/Toolbelt.Blazor.HeadElement#2]
Hi, thank you for the great lib.
When I create Title with for example polish chars eg. ą,ś,ć,ę - title render blank

<Title>Darmowe zdjecia</Title> works correct
but
<Title>Darmowe zdjęcia</Title> render <title></title> in html

With Meta everything works ok.

Best regards.

**Comment by jsakamoto** [comment]
Thank you for your report!

I fixed this problem just now.

Could you try to "Blazor Head Element Helper" **ver.1.1.1**?

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/1.1.1

**Comment by gaffkins** [comment]
Thank you so much. 
It works very well.
Best!
