### ISSUE TITLE
Can only include one HrefLang tag (cannot implement recommended pattern)

### ISSUE THREAD

**Issue by EricBos** [jsakamoto/Toolbelt.Blazor.HeadElement#24]
It is recommended to include the current language of a page in the hreflang as well as a link for each and every other language version of a page.

With the current implementation the Hreflang Link elements are overwriting itself.

I think it's because of the code below:

 ```
const linkComparer = {
            canonical: () => true,
            prev: () => true,
            next: () => true,
            icon: (m, a) => ('' + m.sizes) === a.s,
            alternate: (m, a) => m.type === a.p && m.media === a.m,
            preload: (m, a) => getAttr(m, href) === a.h && m.media === a.m,
        };
```

Shouldn't the HrefLang also be part of the link comparison?

**Comment by jsakamoto** [comment]
@EricBos 
Thank you for letting me know! 👍 
Yes, you are right, I could not realize it until I received your issue post, but HrefLang had to be a part of the link comparison.

I'll fix the "Blazor Head Element Helper" libraries about this point in the near future.

**Comment by EricBos** [comment]
Awesome! I'll wait for the release then

**Comment by jsakamoto** [comment]
It took a long time, but I did it.
I published v.6.0.1 of these libraries on the nuget.org.

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/6.0.1
- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement.Services/6.0.1
- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement.ServerPrerendering/6.0.1

Please try it out.

**Comment by EricBos** [comment]
No complaints here regarding the speed!
Just upgraded my project and it seems to work!

#superhappy

Met vriendelijke groet,​
ing.
Eric
Bos
Partner | CTO
T:
+31 (0) 20 658 95 98<tel:+31%20(0)%2020%20658%2095%2098>
 |
M:
+31 (0)6 11 741 719<tel:+31%20(0)6%2011%20741%20719>
***@***.***
springrealestate.com<https://springrealestate.com/>
 |
LinkedIn<https://www.linkedin.com/company/spring-real-estate/>
 |
Facebook<https://www.facebook.com/springrealestatebv/>
 |
Instagram<https://www.instagram.com/spring_real_estate/>
***@***.***
Spring Real Estate
Laan der Hesperiden 68
 |
1076 DX
 |
Amsterdam
Spring Real Estate is een handelsnaam van Spring Services B.V., ingeschreven in het handelsregister van de Kamer van
​Koophandel te Amsterdam onder nr. 34382962.

​Disclaimer ‑ Deze email en mogelijk meegezonden bestanden zijn vertrouwelijk en bevatten informatie die alleen bedoeld is
​voor de geadresseerde. Heeft u deze email ontvangen en bent u niet de geadresseerde, stel dan de zender van de email op de
​hoogte via email of telefoon (+31 (0)20 658 95 98) en verwijder deze email van uw systeem. Wij kunnen niet garanderen dat
​deze email en mogelijk meegezonden bestanden virusvrij zijn, ondanks dat wij daar grote zorg aan besteden om dit risico zo
​beperkt mogelijk te houden.

**Comment by EricBos** [comment]
Confirmed!
