### ISSUE TITLE
[Bug] 7.1.0 - <meta> content attribute value becomes empty and gets replaced by media attribute which gives unexpected results in browser

### ISSUE THREAD

**Issue by fingers10** [jsakamoto/Toolbelt.Blazor.HeadElement#30]
After upgrading to 7.1.0, `content` attribute of normal `<meta>` element in `index.html` gets replaced by `media` attribute and the `content` attribute value becomes empty in `blazor wasm` apps and this produces unexpected results in browser. 

Example,

This,

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

Becomes,

```html
<meta name="viewport" media="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" content="" />
```

This breaks the responsiveness of the site.

All the `<meta>` tags in `index.html` gets affected.

**`<meta>` tags in `index.html` with `content` attribute**

```html
<meta name="author" content="Abdul Rahman Shabeek Mohamed">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta name="copyright" content="I Love DotNet">
<meta name="language" content="EN">
<meta name="robots" content="index,follow" />
<meta name="owner" content="Abdul Rahman Shabeek Mohamed">
<meta http-equiv="Content-Security-Policy"
      content="base-uri 'self';
           block-all-mixed-content;
           img-src data: 'self';
           object-src 'none';
           script-src 'self'
                      https://gist.github.com
                      'unsafe-eval'
                      'unsafe-inline'
                      data:;
           style-src 'self'
                     https://github.githubassets.com
                     'unsafe-inline';
           upgrade-insecure-requests;">
```

**`<meta>` tags in `index.html` with `content` attribute replaced by `media` attribute and `content` attribute value becomes empty**

```html
<meta name="author" media="Abdul Rahman Shabeek Mohamed" content="">
<meta name="viewport" media="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" content="">
<meta name="copyright" media="I Love DotNet" content="">
<meta name="language" media="EN" content="">
<meta name="robots" media="index,follow" content="">
<meta name="owner" media="Abdul Rahman Shabeek Mohamed" content="">
<meta http-equiv="Content-Security-Policy" media="base-uri 'self';
               block-all-mixed-content;
               img-src data: 'self';
               object-src 'none';
               script-src 'self'
                          https://gist.github.com
                          'unsafe-eval'
                          'unsafe-inline'
                          data:;
               style-src 'self'
                         https://github.githubassets.com
                         'unsafe-inline';
               upgrade-insecure-requests;" content="">
```

**Comment by jsakamoto** [comment]
@fingers10 
Thank you for reporting! 

However, unfortunately, I was not able to reproduce the problem that you reported even though I spent a lot of hours. 😥

This problem looks not so obvious.

Could you tell me more details about your project, such as the target framework version (Core3.1, 5.0, 6.0, etc.), runtime type (Blazor server or Blazor WebAssembly), and your app is PWA or not, etc.

Of course, attaching the zipped project file that is minimal to reproduce the problem into this thread is much helpful to figure out the reason for the problem.

**Comment by jsakamoto** [comment]
@fingers10 
Thank you for providing the URL of your repository to reproduce the problem.

However, unexpectedly, that project worked well in my local environment.

![image](https://user-images.githubusercontent.com/95908/162966508-ccdbd352-ba6c-42e7-9e99-a5ced4282d22.png)

So I have a question.

In your environment, in the "Service Workers" section of the "Application" tab, of the browser's developer tools window, is there any service worker registered?

![image](https://user-images.githubusercontent.com/95908/162966416-ed75317f-e75f-44b2-a290-ead91386e596.png)

If it is yes, then could you try out the following steps?

**1.** Please unregister the service worker.

![image](https://user-images.githubusercontent.com/95908/162966060-7db3240a-04cf-4c8e-8b32-25d5f6eb1d74.png)

**2.** Clear all of the caches of the Blazor application.

![image](https://user-images.githubusercontent.com/95908/162966024-d8353257-dc80-42d6-875c-c3344335629e.png)

**3.** Close all web browser tabs and windows.

**4.** Re-launch the web browser, and after opening the app, set the "Disable cache" check box in the "Network" tab and hard reload it.
![image](https://user-images.githubusercontent.com/95908/162965961-afe873cf-44a5-4cf2-8245-b78a25c476c8.png)

I hope the app will work fine once after doing that.

**Comment by fingers10** [comment]
@jsakamoto did you publish the project and running it from iis?

**Comment by jsakamoto** [comment]
@jsakamoto 

I did the `dotnet publish -c:Release` command, and serve the published contents files by using `dotnet serve` global tool like this:

```
dotnet serve -d:"bin/Release/net6.0/publish/wwwroot" -S
```

I did not make it run on IIS.

**Comment by fingers10** [comment]
@jsakamoto ,

Many thanks for your time and response, Here are the response to previous questions.

I have no service workers registered.

![image](https://user-images.githubusercontent.com/43729469/163022898-f9d49e9c-b165-44a2-ae6b-e1d8c7407883.png)

Disabled cache and did a hard reload

![image](https://user-images.githubusercontent.com/43729469/163023043-3ad3edb8-b6b0-4ecc-aa18-c82fd3c755eb.png)

Published and running in IIS/ GitHub Pages. Issue occurs in both

![image](https://user-images.githubusercontent.com/43729469/163023259-d1300d64-bd0f-4671-b9b0-68e855dac761.png)

As you can see from above image,

```html
<meta name="viewport" media="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" content="">
```

but `index.html` has

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

This breaks the responsiveness of page.

**Comment by jsakamoto** [comment]
@fingers10 Thanks for the excellent reporting!

Due to your contribution, I found a critical bug in this library!

Could you try out the latest version?

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/7.1.1

**Comment by fingers10** [comment]
@jsakamoto that works. many thanks for your time and efforts to look on to this. 

This is optional - I would be more happy if you could write a recommendation to me on linkedin if you find my contributions are worthy.
