### ISSUE TITLE
Changelogs not found

### ISSUE THREAD

**Issue by thepra** [jsakamoto/Toolbelt.Blazor.HeadElement#31]
Hi, I was just wondering if you have any place where I could look up the changelog of each new release of the library, there's such place?
Otherwise I just wonder what was done behind the scenes when I upgrade such library.

**Comment by jsakamoto** [comment]
@thepra Sorry for the late reply!

Actually, there are release notes for each NuGet package about the "Blazor Head Element".
Please see the following links.

- **Absctractions** - https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement/blob/master/Abstractions/RELEASE-NOTES.txt
- **Services** - https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement/blob/master/Services/RELEASE-NOTES.txt
- **Components** - https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement/blob/master/Components/RELEASE-NOTES.txt
- **Server Prerendering** - https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement/blob/master/ServerPrerendering/RELEASE-NOTES.txt

And the "nuget.org" site has a "Release Notes" view for each NuGet package.

![image](https://user-images.githubusercontent.com/95908/166454409-ae93e910-3a3a-4bc3-acac-271ae9fe781f.png)

The guiding line of the "Release Notes" view on the nuget.org site said that only the latest changelog should be described on the "Release notes" view, so I've followed it.

Anyway, I agree that those release notes are not easy to access.
So I would like to improve the accessibility of those release notes in the future.
