### ISSUE TITLE
It is possible to create http-equiv metas? 

### ISSUE THREAD

**Issue by emiliovmq** [jsakamoto/Toolbelt.Blazor.HeadElement#4]
It is possible to create http-equiv metas? like, for instance:

`<meta http-equiv="refresh" content="3;url=https://www.mozilla.org">`
or
`<meta charset="utf-8">`

Thanks

**Comment by jsakamoto** [comment]
@emiliovmq 

I published `<meta http-equiv />` supported version just now.

- https://www.nuget.org/packages?q=Toolbelt.Blazor.HeadElement

Those are Beta release at this time, but I'll make it as official release when I get confident.

Thank you for your pull request, @pacas00 !

**Comment by jsakamoto** [comment]
@emiliovmq @pacas00 

Today, I published the latest official release version.

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/1.2.0

Thanks for all!
