### ISSUE TITLE
HeadElement depends on Toolbelt.Blazor.HotKeys?

### ISSUE THREAD

**Issue by thepra** [jsakamoto/Toolbelt.Blazor.HeadElement#40]
I'm having this exception when the only toolbelt library that I use is HeadElement:
![2022-12-15 23_28_27-DevTools - localhost_7046_](https://user-images.githubusercontent.com/7032509/207981618-d14d9fc4-7a64-4ef6-9020-9e45d3711bad.png)

How can I fix it without installing HotKeys?

**Comment by jsakamoto** [comment]
@thepra Thank you for reporting!

It's my fault, it is just typo!

- https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement/blob/a99e4b95381bad2c75ee9be95a3c8b04e3ddd235/Services/HeadElementHelperService.cs#L101

It has to be "...**Head**.ready", not "...**HotKeys**.ready"!

I will fix it as soon as possible.

**Comment by jsakamoto** [comment]
@thepra I fixed this embarrassing bug today, and I published the fixed latest version, ver.7.3.1, right now. 

- https://www.nuget.org/packages?q=HeadElement

Could you check it out?
Again, thank you for your contributions!

**Comment by thepra** [comment]
Yep, dependency and error gone :)
